apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  ports:
    - nodePort: 32000
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: nginx
  type: NodePort
