apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: vintage-car-booking:/Service:vintage-car/todo-service
  name: todo-service
  namespace: abhi
  namespace: default
spec:
  ports:
    - nodePort: 32000
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: nginx
  type: NodePort
