apiVersion: apps/v1
kind: Deployment
metadata:
  name: vintage-car-booking

spec:
  replicas: 2

  selector:
    matchLabels:
      app: vintage-car-booking

  template:
    metadata:
      labels:
        app: vintage-car-booking

    spec:
      containers:
        - name: vintage-car-booking
          image: docker.io/abhi7677/vintage-car-booking:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: vintage-car-booking-service

spec:
  selector:
    app: vintage-car-booking

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort
